# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish odyssey-locale to npm

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  schedule:
    - cron: '30 11 * * 4'

jobs:
  tests:
    name: Tests
    needs: code-analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.3]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run tests
        run: yarn test
      
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
